---
title: "Download fianal data "
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
editor: visual
execute:
  eval: false
  echo: true
  warning: false
  message: false
---

# Download fianal data

"The final cleaned and labelled dataset was exported in R (.rds)/SPSS (.sav)/ Stata (.dta) format to ensure operability across analytical platforms.”

#### Load library

```{r}

# install.packages(c("haven", "labelled", "rio"))
library(haven)
library(labelled)
library(rio)

```

#### R FORMAT (BEST FOR REPRODUCIBILITY)

```{r}
save(df, file = "final_dataset.RData")
# to load use - 
# load("final_dataset.RData")
```

#### SPSS FORMAT (.sav)

```{r}
write_sav(df, "final_dataset.sav")

```

#### STATA FORMAT (.dta)

```{r}
write_dta(df, "final_dataset.dta")
```

#### CSV FORMAT (.csv)

warning - variable labels and ref cat will be lost

```{r}
write.csv(df, "final_dataset.csv", row.names = FALSE)
# best practise to download datadictionary so that the labels wont be missed 

data_dictionary <- tibble(
  variable = names(df),
  label = sapply(df, function(x) attr(x, "label")),
  class = sapply(df, class)
)

write.csv(data_dictionary, "data_dictionary.csv", row.names = FALSE)


```

#### Export all formats

```{r}
export_all_formats <- function(df, name = "final_dataset") {
  saveRDS(df, paste0(name, ".rds"))
  write_sav(df, paste0(name, ".sav"))
  write_dta(df, paste0(name, ".dta"))
  write.csv(df, paste0(name, ".csv"), row.names = FALSE)
}
export_all_formats(df)

```